### ISSUE TITLE
Source code for modpack building is not present in the repository

### ISSUE THREAD

**Issue by forkiesassds** [Legacy-Union/Re-Console#10]
What's the point of having a repository for this project if the code for building the modpack packages for various launchers is not present in the repo?

**Comment by omo50** [comment]
It's actually hard to make an open source modpack as I do not have permissions to redistribute most mods. This serves as an issue tracker.

It is planned in the future to put the modified config files here so that people can take and use them.

**Comment by forkiesassds** [comment]
> It's actually hard to make an open source modpack as I do not have permissions to redistribute most mods. This serves as an issue tracker.

Well, it's possible to just use something like packwiz or unsup to store configuration for how a mod inside a modpack should be deployed
