### ISSUE TITLE
mod menu crash

### ISSUE THREAD

**Issue by Spincial** [Legacy-Union/Re-Console#12]
scrolling to the bottom of the mod menu causes an immediate crash

**Comment by IEatSoulsMeow** [comment]
I've had the same problem. 
Crash log: https://pastebin.com/3af8X6Nx

**Comment by omo50** [comment]
this issue is with MoreCulling in specific, which i wont fix due to the performance boost that the mod gives

**Comment by omo50** [comment]
fixed in 0.4.0
