### ISSUE TITLE
Dualshock 4 Controller Not Working via Bluetooth on macOS

### ISSUE THREAD

**Issue by evonestel** [Legacy-Union/Re-Console#14]
I'm running macOS 14.4.1 on my MacBook Pro 14" M2 Pro but it is not working at all when it is connected via Bluetooth other controller mods are running perfectly fine with Bluetooth but for some reason, it is not working at all with Re-Console. It is detected since I am getting DS4 glyphs in the UI but not working for any control in the game or in the UI. I also tried to use the controller via USB and it worked fine. I also know the controller works fine with the mod since it works fine via Bluetooth on Arch Linux.

**Comment by nonetrix** [comment]
Also having issues on Linux

**Comment by BazziteUser** [comment]
Change your controller number until you find it. also disable steam input if using it

**Comment by omo50** [comment]
I'm unsure of what I can do to fix this issue as I don't own a MacOS system. I'll see what I can do though? It may be more beneficial to put this on the actual Legacy4J issue tracker

**Comment by omo50** [comment]
I believe what @BazziteUser said may work, actually. Re-Open if issue persists
