### ISSUE TITLE
Boat turning broken on controller

### ISSUE THREAD

**Issue by Un1q32** [Legacy-Union/Re-Console#17]
On a boat if you turn in any direction you will continue to turn in that direction until the left stick is put into the neutral position, even if you try to turn in the opposite direction

**Comment by Jnight2339** [comment]
i was just typing the same bug report 💀

**Comment by Wilyicaro** [comment]
This is not an issue with Re-Console, but with Legacy4J, anyway this will be fixed in version 1.6.3
