### ISSUE TITLE
Legacy Crafting interface is inexplicably force disabled after a little bit of gameplay. Unable to be turned back on without restarting

### ISSUE THREAD

**Issue by JuniperIsSleepy** [Legacy-Union/Re-Console#20]
For some reason my crafting interface is forced back into classic crafting shortly after entering the game. I am unsure if death is the trigger or something else, but it is extremely annoying and recurs each time. Please help?

**Comment by omo50** [comment]
mind giving me logs after this happens so i can get info (Upload to mcl.ogs pls)

**Comment by JuniperIsSleepy** [comment]
Yeah sure thing, I’ll get to it when I can. It’s possible its also an issue with the 4j mod itself which I will also test.

**Comment by JuniperIsSleepy** [comment]
https://mclo.gs/3qf5PY9 i cant see anything useful here, but maybe you can. I will now test with only legacy4j installed.

**Comment by JuniperIsSleepy** [comment]
https://mclo.gs/ikNj09d same thing happened with only a couple perf mods and legacy4j, might need to forward this to the legacy4j dev

**Comment by omo50** [comment]
these logs give me nothing to work with. Seems as if its a L4J Issue and not a Re-Console one? I see you opened an issue on that repo so ill mark this as closed. re-open if something comes up
