### ISSUE TITLE
Classic Crafting Keeps getting turned on

### ISSUE THREAD

**Issue by SeventhEntropy** [Legacy-Union/Re-Console#23]
I'm playing with an Xbox one controller and as I'm playing the classic crafting option keeps getting turned on randomly, and I don't want to use it. Is there like a controller macro that switches it or like a keyboard shortcut that I don't know about?

**Comment by SeventhEntropy** [comment]
It seems to be happening whenever I try to go to the crafting menu with X instead of using a crafting table

**Comment by JuniperIsSleepy** [comment]
https://github.com/Wilyicaro/Legacy-Minecraft/issues/321

**Comment by omo50** [comment]
#20
