### ISSUE TITLE
Crashes on AMDGPU

### ISSUE THREAD

**Issue by DBTDerpbox** [Legacy-Union/Re-Console#24]
ImmediatelyFast can crash on AMDGPU on Linux

Its up to you how you handle this, but here's the issue on ImmediatelyFast's GitHub repo: [https://github.com/RaphiMC/ImmediatelyFast/issues/183](https://github.com/RaphiMC/ImmediatelyFast/issues/183)

Here's a log if its any help [https://mclo.gs/k8VyH4C](https://mclo.gs/k8VyH4C)

**Comment by omo50** [comment]
hm. will have to look into how id exactly handle this? strange bug. I wouldnt like to remove the mod (as it does wonders performance wise)

Its also hard for me to work on a workaround if even possible due to me not running Linux or a AMD GPU

**Comment by DBTDerpbox** [comment]
I decided to test ImmediatelyFast by itself and it doesn't seem to crash, so its some combination of mods causing it

**Comment by omo50** [comment]
Mind testing with Faster Random, Nvidium and IF? FR and Nvidium come to mind as they are the most recent additions

I will probably remove nvidium in the next version until a 1.20.6 port due to it having a memory leak on linux systems

**Comment by omo50** [comment]
also apologies for having you test, i just do not have the requirements to test myself 😅

**Comment by DBTDerpbox** [comment]
Its fine, I'm the one who made the report

**Comment by DBTDerpbox** [comment]
After a lot of testing, this seems to be caused by the config file you have for ImmediatelyFast

I'll do some more testing to try to figure out what specifically is wrong with it

**Comment by omo50** [comment]
@DBTDerpbox Maybe look at disabling the experimental options "experimental_disable_error_checking" and "experimental_disable_resource_pack_conflict_handling"?
Id also mess with increasing "fast_buffer_upload_size" to 128, although i heavily doubt thats causing it

**Comment by DBTDerpbox** [comment]
This seems to be caused by `  "fast_buffer_upload_size_mb": 64,`, everything else is fine

setting it to 128 does work, but the default is 256 so you might want to use that instead

**Comment by omo50** [comment]
the   "fast_buffer_upload_size_mb" is iirc how often IF refreshes hud elements in some way. Unsure of what it does exactly, all i know is generally lower values = faster hud elements and better performance. 0.3.2 should release later with this change to 128. Thanks for your help

**Comment by omo50** [comment]
let me know if any other issues occur 👍
