### ISSUE TITLE
extreme fps drops when loading chunks

### ISSUE THREAD

**Issue by Twalla78** [Legacy-Union/Re-Console#27]
even at low render distances the fps will just tank sometimes mostly when loading chunks and i have a i7 9700k and a 2080ti and 16gb of ram with all the mods in the pack i should never drop below like 100 frames but sometimes i go down to 20 or it freezes for like 3 secs

**Comment by omo50** [comment]
allocate less ram, protip is to generally not go above 8gb

**Comment by omo50** [comment]
marking as closed cause youve given me like.. no info for nearly a week
feel free to re-open
