### ISSUE TITLE
Console crafting menu doesnt show on servers

### ISSUE THREAD

**Issue by bubbyboom** [Legacy-Union/Re-Console#29]
i used this mod and its superb at its goal its just that when i went on my private server i couldnt use the console crafting which really upset me, why is this?

**Comment by bubbyboom** [comment]
i just realised this also occurs to the attack cooldown, its stuck on hidden

**Comment by Cjnator38** [comment]
Attack cooldown is removed via Golden Age Combat in Re-Console

**Comment by bubbyboom** [comment]
what about the legacy console crafting menu not being available on servers

**Comment by Cjnator38** [comment]
You need to have Re-Console installed on the server if you're using it  If you already have Re-Console on the server, you may need to log out, disable Classic Crafting, and log back in.
