### ISSUE TITLE
Bedrock not generating in 1.12.2

### ISSUE THREAD

**Issue by willmasterLUA** [Legacy-Union/Re-Console#30]
Hi, Me and my friend were playing on a world where the generation was copying the 1.12.2 generation via the "Moderner Beta" Mod.
My friend realized that bedrock isnt generated at all, it just cuts and the void can be entered.
![immagine](https://github.com/Legacy-Union/Re-Console/assets/79755822/57033561-d09e-42e9-9d86-1feb3e0c4f34)

**Comment by omo50** [comment]
this issue was fixed in moderner beta 1.3.1
