### ISSUE TITLE
Boats can't be steered with a controller

### ISSUE THREAD

**Issue by MST298** [Legacy-Union/Re-Console#33]
Pushing any direction on the left stick will make the boat move forward, and the only way to steer the boat is to use a keyboard. If only Legacy4J is installed, you can steer a boat with a controller perfectly well, so I'm not sure what mod causes this problem.

**Comment by Wilyicaro** [comment]
Reset your controller settings, probably because you are using Legacy4J on a clean instance there was no such problem
