### ISSUE TITLE
Consider relicensing to a more restrictive license

### ISSUE THREAD

**Issue by omo50** [Legacy-Union/Re-Console#34]
As of earlier today, I discovered a new console modpack, which was a near complete reupload of Re-Console, albeit it was turned into a closed source, ARR mess with changes so small it likely breaks the Apache 2.0 license terms.

This modpack (of which I will not name) has already been reported to Modrinth for being a de-facto reupload of Re-Console, and as a protective measure for the future, I believe it may be in my (and the projects) best interest to relicense in a way which disallows something like this from happening in the future.

I open this issue for a discussion of what the general opinion is regarding this, and how exactly we should go about this.

**Comment by omo50** [comment]
I still seek for a FOSS license in regards of this project; and the config files will still be public (once uploaded likely tomorrow, GitHub has just been a pain and I haven't bothered yet). I will not be going ARR with this, for anyone wondering

**Comment by Un1q32** [comment]
GPLv3 gud

**Comment by Wilyicaro** [comment]
And also, regarding a more restrictive license, in the case of a modpack, I believe it would be difficult not to have modpacks that are literally copies of each other, just with small changes, the problem in this case is when due credits are not given, as is the case, and there is the change of license, which should not be allowed as it's obviously not compatible with ARR.
In short, I don't think a license change would do anything, but rather better moderation of Modrinth

**Comment by omo50** [comment]
> And also, regarding a more restrictive license, in the case of a modpack, I believe it would be difficult not to have modpacks that are literally copies of each other, just with small changes, the problem in this case is when due credits are not given, as is the case, and there is the change of license, which should not be allowed as it's obviously not compatible with ARR. In short, I don't think a license change in Re-Console would do anything, but rather better moderation of Modrinth

There is no issue with similar modpacks; there is an issue with a near-direct reupload of one mod pack, claiming the work is yours (when it isn't) then giving minimal credit and making it closed source. This is merely a defensive measure, at least in my eyes

**Comment by Un1q32** [comment]
> I don't think a license change in Re-Console would do anything, but rather better moderation of Modrinth

This is the case for all software unless you can pay lawyers, your license is just some text file otherwise, but if we're going to have any text file we might as well have the best one (GPLv3)

**Comment by Wilyicaro** [comment]
> There is no issue with similar modpacks; there is an issue with a near-direct reupload of one mod pack, claiming the work is yours (when it isn't) then giving minimal credit and making it closed source. This is merely a defensive measure, at least in my eyes

Of course there isn't, I haven't discussed similar modpacks, but rather not giving a license and still making it closed source and even ARR, which is not legally allowed, because the Re-Console license doesn't allow this kind of thing, but what I meant was, there's no point in changing the license if you won't have the guarantee that it will be complied with.

**Comment by omo50** [comment]
> > There is no issue with similar modpacks; there is an issue with a near-direct reupload of one mod pack, claiming the work is yours (when it isn't) then giving minimal credit and making it closed source. This is merely a defensive measure, at least in my eyes
> 
> Of course there isn't, I haven't discussed similar modpacks, but rather not giving a license and still making it closed source and even ARR, which is not legally allowed, because the Re-Console license doesn't allow this kind of thing, but what I meant was, there's no point in changing the license if you won't have the guarantee that it will be complied with.

A relicense to a more defined, restrictive license does mean that I can send out reports that are more likely to take down stuff like this in the future, if I am not mistaken

That would be the way this gets enforced

**Comment by theminecraftarchitect** [comment]
I agree with omo and Willy. I think re-licensing to FOSS or similar will hopefully allow for more successful take-downs if this were to occur in the future. Yes, Modrinth moderation could be better and there's no guarantee someone will make a new pack that is just a reskin of Re-Console. However, it's better to try to protect the pack than just let knockoff packs get away with a cheap copy.

**Comment by Un1q32** [comment]
@theminecraftarchitect Relicensing to FOSS?  It's already FOSS and they said they didn't want the new license to not be FOSS.  The GPLv3 is about as restrictive as you can get without using a non-FOSS license as it restricts forks from being closed source.

**Comment by theminecraftarchitect** [comment]
> @theminecraftarchitect Relicensing to FOSS? It's already FOSS and they said they didn't want the new license to not be FOSS. The GPLv3 is about as restrictive as you can get without using a non-FOSS license as it restricts forks from being closed source.

Sorry, I meant a different version of FOSS

**Comment by omo50** [comment]
The decision has been made to relicense, thanks for the input
