### ISSUE TITLE
Ingot section order doesn't really make sense

### ISSUE THREAD

**Issue by psychoshay** [Legacy-Union/Re-Console#36]
![Screenshot 2024-05-17 135723](https://github.com/Legacy-Union/Re-Console/assets/169887728/58c4dffe-0406-4ee2-844d-053e218de3ea)

List currently goes kelp, gold, iron, netherrite, copper, diamond etc which seems very wrong?

Ignore everything non vanilla I am making recipes for a mod

**Comment by omo50** [comment]
this is a thing to put in the L4J repo, not the Re-Console one 
https://github.com/Wilyicaro/Legacy-Minecraft

**Comment by psychoshay** [comment]
> this is a thing to put in the L4J repo, not the Re-Console one https://github.com/Wilyicaro/Legacy-Minecraft

Ah sorry
