### ISSUE TITLE
Crash when attempting to configure Borderless Mining through Mod Menu

### ISSUE THREAD

**Issue by Cjnator38** [Legacy-Union/Re-Console#37]
Mod Menu accessed via hotkey
[crash-2024-05-17_08.56.44-client.txt](https://github.com/Legacy-Union/Re-Console/files/15350419/crash-2024-05-17_08.56.44-client.txt)

**Comment by omo50** [comment]
mind uploading to mclo.gs?

**Comment by omo50** [comment]
will replace borderless mining in 0.3.6
