### ISSUE TITLE
books are not working properly

### ISSUE THREAD

**Issue by zipzopbeesopdro** [Legacy-Union/Re-Console#39]
in a book it doesnt let me select options. i think its because of the different ui

![image](https://github.com/Legacy-Union/Re-Console/assets/73306261/23722f9b-72b1-4452-a2ad-b93f868a0900)

**Comment by omo50** [comment]
LEM and Re-Console (Legacy4J as a whole) is not compatible with the LEM minigame network as of now. Compatibility is being worked on, but it currently has major bugs
