### ISSUE TITLE
Word stuck loading

### ISSUE THREAD

**Issue by KJ76539** [Legacy-Union/Re-Console#4]
Either its very long or its stuck cause i spent about 30 minutes waiting on it to load.

**Comment by omo50** [comment]
unless you give me logs i cant help with this one

**Comment by KJ76539** [comment]
[2024-05-03-1.log.gz](https://github.com/Legacy-Union/Re-Console/files/15206628/2024-05-03-1.log.gz)

**Comment by omo50** [comment]
Upload that to mclo.gs please

**Comment by KJ76539** [comment]
https://mclo.gs/1JM0Gf4

**Comment by omo50** [comment]
...this says that it took ~20 seconds?

**Comment by KJ76539** [comment]
it was still loading when i decided closed it out. might be something with the loading screen idk

**Comment by KJ76539** [comment]
ill reinstall and try to see if it works

**Comment by omo50** [comment]
its been a week, closing
