### ISSUE TITLE
can't repeatedly craft whilst holding "A" on my controller

### ISSUE THREAD

**Issue by NKillHere** [Legacy-Union/Re-Console#40]
Sounds minor, but I can't craft quickly without it. It's as specified, I can't hold A to repeat my crafting command

**Comment by NKillHere** [comment]
forgot to add smth, If you need like a video showcasing it, then just ask.

**Comment by omo50** [comment]
this is (what i believe to be) a Legacy4J issue
https://github.com/Wilyicaro/Legacy-Minecraft/issues

**Comment by NKillHere** [comment]
Idk, on a different modpack that also used Legacy4J it worked fine, that's why I came to think it was a re-console issue
