### ISSUE TITLE
fullscreen resolution change does not work

### ISSUE THREAD

**Issue by BlueSupernova22** [Legacy-Union/Re-Console#43]
I have a 1440p monitor and sometimes play on a 4k tv (silly i know) and on vanilla i usually play on 1080p and have my radeon software do some up scaling to save performance. however when using this modpack changing the fullscreen resolution setting doesn't do anything even when i exit and re enter fullscreen. i dont know if one of the mods in the pack is interfering with that setting, but if there is then let me know as this problem does not happen when i play with only just the L4J mod.

**Comment by DanielMC101** [comment]
you gotta exit out of the fullscreen, then fullscreen again.

**Comment by BlueSupernova22** [comment]
as i clearly stated in my comment exiting and re entering fullscreen does nothing.

my monitor resolution is set at 1440p
![res](https://github.com/Legacy-Union/Re-Console/assets/57787046/9331a940-6583-4561-83b4-b547f57057f6)

here i have the ingame setting set to 1080
![mc issue](https://github.com/Legacy-Union/Re-Console/assets/57787046/969a4379-c575-4f60-8a7e-6bdc6e17ed37)

this was taken using my phone since i cant screenshot the radeon hud but as you can see the radeon super resolution upscale effect is not active which mean the in game resolution is not changing to the lower one im setting it to
![20240519_220046](https://github.com/Legacy-Union/Re-Console/assets/57787046/4c6757b1-1d28-4302-b38e-733f6f257d44)

**Comment by omo50** [comment]
This is due to borderless mining (iirc), disable the mod if you want to change resolution

**Comment by natopotato390** [comment]
> This is due to borderless mining (iirc), disable the mod if you want to change resolution

Hey, fantastic modpack!
I'm having this issue with latest release. I don't see any mod named "borderless mining". how can I circumvent this?

changing the resolution seems like a pretty important feature that shouldn't require any tweaking of the modpack.
i personally want to set it to 720p to get that authentic x360 experience
