### ISSUE TITLE
Time will freeze, often near a village

### ISSUE THREAD

**Issue by BlueKnight117** [Legacy-Union/Re-Console#45]
while playing with the Re-Console modpack i have occasionally run into the issue where once i have gone near a village, all entities freeze, blocks do not drop, i cannot use anything interactable (chests, furnaces, etc), and i am unable to die, the only extra mods i am running alongside this is Freecam, Zoomify, and Enchantment Compatibility

**Comment by omo50** [comment]
I cant really help without info like logs. This issue is weird and i cant repro as of 0.4.3

**Comment by omo50** [comment]
As ive never been able to reproduce this, i believe this may be a hardware issue on your end. Closing
