### ISSUE TITLE
[Mod Suggestion] Essential

### ISSUE THREAD

**Issue by csd-was-taken** [Legacy-Union/Re-Console#46]
[Essential](https://modrinth.com/mod/essential) is a mod with a lot of features (that should probably be turned off for this modpack), but the key one is the ability to locally host a server for your friends to join, just like how it worked on legacy console.

I'm not sure if the UI for essential could be changed, or if there's another mod that would do the same thing without requiring such a bloated mod for a single feature, but it could be worth looking into

**Comment by omo50** [comment]
E4MC is already in the modpack
Open world to LAN and send the e4mc link to your friends
