### ISSUE TITLE
Open to LAN option not working on customized worlds

### ISSUE THREAD

**Issue by RubenHutten** [Legacy-Union/Re-Console#47]
When loading a world with customized generation the Open to LAN setting will not properly work. The world will load normally but no LAN server will be started. I assume this is due to the warning screen that gets shown when loading a customized world. A current way to get around this issue is to use a mod that removes this warning.

**Comment by omo50** [comment]
>  A current way to get around this issue is to use a mod that removes this warning.
No mods that do that at this point in time work with Legacy4J. This issue also makes no sense, as customized worlds do not affect in any shape or form the LAN aspect of the game
