### ISSUE TITLE
Game/World crash while using quick crafting

### ISSUE THREAD

**Issue by CombatPainter** [Legacy-Union/Re-Console#5]
Crash occurs when stackable or non-stackable item is crafted in quick craft menu while the inventory is full and has no empty slot or existing item stack to go into.
![re-console](https://github.com/Legacy-Union/Re-Console/assets/83049988/d26a4cfb-0322-4365-bb9a-9911e2e2f39c)

**Comment by CombatPainter** [comment]
Just tested on the base Legacy4J mod and this crashing issue did not occur

**Comment by omo50** [comment]
Are you on 0.2.3? C2ME was disabled with 0.1.3

**Comment by CombatPainter** [comment]
Yeah I ran into it on both version 2.2 and 2.3. After looking at Prism Launcher, C2ME does show up as disabled in the mod list so I'm really not sure why it would still be in effect.

**Comment by CombatPainter** [comment]
> Yeah I ran into it on both version 2.2 and 2.3. After looking at Prism Launcher, C2ME does show up as disabled in the mod list so I'm really not sure why it would still be in effect.

After doing a bit more digging I've found that the crash comes from ishland's Unsafe World Random Access Detector mod. After I disabled it the crashes went away.

**Comment by omo50** [comment]
Thanks! Had thought it was C2ME as they have the same author (ishland) and it sounded like a similar issue. will look into later

**Comment by omo50** [comment]
fixed in 0.3
