### ISSUE TITLE
Add nostalgic tweaks by Adrenix

### ISSUE THREAD

**Issue by SpectralPixel** [Legacy-Union/Re-Console#50]
Nostalgic Tweaks is a mod that adds options to configure gameplay to be more fitting with older versions of Minecraft.
It is easily configurable (without the need of a dedicated configuration menu mod) by pressing the `o` key (o for old).
I feel like this addition would contribute to the nostalgic feel of the mod, and also help users create their own optimal experience.
Link: https://github.com/Adrenix/Nostalgic-Tweaks

**Comment by omo50** [comment]
I know of the existence of the mod and use it in another modpack of mine.

This project is if Legacy Console Edition never ended; not a re-creation of old mc. Nostalgic Tweaks is an amazing mod but doesnt fit the theme of Re-Console
