### ISSUE TITLE
Weird input stuttering on keyboard and mouse input

### ISSUE THREAD

**Issue by Cjnator38** [Legacy-Union/Re-Console#51]
On the latest Re-Console, keyboard and mouse input suffers from massive input stutters. These stutters are especially apparent when first opening a world. Controller doesn't seem to have this issue. Latest stock L4J and Adrenaline also do not have this issue.
Re-Console: https://streamable.com/8d50sa
Latest Legacy4J: https://streamable.com/5rnshq

**Comment by omo50** [comment]
Odd. Mind disabling Debugify and trying? I havent seen this as an issue on my personal instance

**Comment by Cjnator38** [comment]
Might just be a polling rate issue, still weird that it only seems to affect Re-Console instances. I'll try without Debugify

**Comment by omo50** [comment]
On polling rate; what hz is your mouse and keyboard? @Cjnator38

The average should be 1000, if its below that it may explain the problem

**Comment by Cjnator38** [comment]
Below 1000 hz should solve the issue if anything. I've always used 1000 hz without any problems until recently

**Comment by Cjnator38** [comment]
That's the mouse's polling rate, for the keyboard idk

**Comment by omo50** [comment]
> Below 1000 hz should solve the issue if anything. I've always used 1000 hz without any problems until recently

below 1000hz would logically make this worse as it checks for input less often, which is what polling rate is
1000hz = 1000 times a second

**Comment by Cjnator38** [comment]
1000 hz polling rate was an issue for AntVenom (https://www.youtube.com/watch?v=5v4zMOQ-sSU). I checked Task Manager and loading chunks takes up nearly 90% CPU usage (at least on Windows), meaning that a higher polling rate would cause stuttery inputs.

**Comment by omo50** [comment]
i generally think this issue may be a problem to your system specifically? I cant repro in any regard

**Comment by Cjnator38** [comment]
It didn't seem to be an issue on my Linux install, and my Logitech software got updated recently so that could also be a culprit. Still need to do further testing

**Comment by omo50** [comment]
> It didn't seem to be an issue on my Linux install, and my Logitech software got updated recently so that could also be a culprit. Still need to do further testing

If you have a spare keyboard or mouse laying around id try that

**Comment by Cjnator38** [comment]
I think 0.4.3 fixed it somehow 💀💀
