### ISSUE TITLE
Maps don't have "borders"

### ISSUE THREAD

**Issue by ChamiIion** [Legacy-Union/Re-Console#55]
Idk how to say it but basically the whole map surface has the preview of what the map looks like meanwhile maps on console editions have a smaller preview, most likely so that the coordinates would be more visible and so that the coordinates wouldn't obstruct the map preview nor the player heads
![image](https://github.com/Legacy-Union/Re-Console/assets/145168195/e2cc5e67-d4f9-4dcd-adf1-92c4927a6a18)
![image](https://github.com/Legacy-Union/Re-Console/assets/145168195/cb2562b3-b0fd-4d91-b52c-c3598e14a4e4)

**Comment by Goodguy140** [comment]
I believe in the next gen version of LCE when the expanded the world they made it like the first image once you explore outside the “classic” world size.

**Comment by ChamiIion** [comment]
I'm pretty sure it still has the "borders"
Imma check the newest version of PS4 hold on

**Comment by ChamiIion** [comment]
Ok you are right... I was so sure that this had borders on ps4 version as well. 😅
