### ISSUE TITLE
No Controller Support?

### ISSUE THREAD

**Issue by DicedTea** [Legacy-Union/Re-Console#6]
Title says it all.

I tried using my xbox controller to play, and it didn't work. I looked through the mod list and there is no controller mod. How can you have a console edition modpack and not have controller support?

The modpack is wonderfully well done but I can't fathom how this is left out.

**Comment by omo50** [comment]
This is an issue with Legacy4J on linux. This is due to the controller libraries and API's used, which is unfixable on my end as i am not a Legacy4J developer

**Comment by tristann21** [comment]
> Title says it all.
> 
> I tried using my xbox controller to play, and it didn't work. I looked through the mod list and there is no controller mod. How can you have a console edition modpack and not have controller support?
> 
> The modpack is wonderfully well done but I can't fathom how this is left out.

What distro were you using?

**Comment by DicedTea** [comment]
> > Title says it all.
> > I tried using my xbox controller to play, and it didn't work. I looked through the mod list and there is no controller mod. How can you have a console edition modpack and not have controller support?
> > The modpack is wonderfully well done but I can't fathom how this is left out.
> 
> What distro were you using?

Opensuse Tumbleweed. I use the prism launcher flatpak.

**Comment by tristann21** [comment]
> > > Title says it all.
> > > I tried using my xbox controller to play, and it didn't work. I looked through the mod list and there is no controller mod. How can you have a console edition modpack and not have controller support?
> > > The modpack is wonderfully well done but I can't fathom how this is left out.
> > 
> > 
> > What distro were you using?
> 
> Opensuse Tumbleweed. I use the prism launcher flatpak.

Isn't opensuse based off of RHEL?

**Comment by DicedTea** [comment]
> > > > Title says it all.
> > > > I tried using my xbox controller to play, and it didn't work. I looked through the mod list and there is no controller mod. How can you have a console edition modpack and not have controller support?
> > > > The modpack is wonderfully well done but I can't fathom how this is left out.
> > > 
> > > 
> > > What distro were you using?
> > 
> > 
> > Opensuse Tumbleweed. I use the prism launcher flatpak.
> 
> Isn't opensuse based off of RHEL?

No, Opensuse is its own distribution. RHEL is based off of Fedora.
